export enum USER_ACTION_TYPES {
    FETCH_USERS = 'FETCH_USERS',
    FETCH_USERS_DONE = 'FETCH_USERS_DONE',
    SET_USERS = 'SET_USERS',
    FETCH_TODOS = 'FETCH_TODOS',
    FETCH_TODOS_DONE = 'FETCH_TODOS_DONE'
}